version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: mb-crypto-cache
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: mb-crypto-app
    restart: always
    volumes:
      - .:/home/app/mb_crypto
    command: >
      sh -c "python manage.py migrate &&
             make loaddata &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env

volumes:
  data_db:
