# Generated by Django 5.0.1 on 2024-01-25 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("currency_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="currencymodel",
            old_name="code",
            new_name="symbol",
        ),
    ]
